SysPngs = {
    -- {"newcoins/%d.png", 1, 23},
    -- {"levelupeffect/baoguang/baoguang_000%2d.png", 46, 46},
    -- {"levelupeffect/baoguang/baoguang_000%2d.png", 48, 51},
    -- {"levelupeffect/liuguang/liuguang_000%2d.png", 45, 61},
    -- {"commonEffect/light_1/diguang_000%02d.png", 1, 16},
}

CommnonThemeRes = {
	{3, "bigwin.png"},
	{3, "huge_win.png"},
	{3, "masslvewin.png"},
	{3, "apocalyptlcwin.png"},
	{3, "Winning_Gold.png"},
	{3, "Winning_Blue_Diamond.png"},
	{3, "Winning_Purple_Diamond.png"},
	{3, "Winning_Green_diamond.png"},
	{3, "Winning_Red_Diamond.png"},
	{3, "eff_bg.png"},
	{3, "massive_win_bg.png"},
	{3, "huge_win_bg.png"},
	{3, "big_win_bg.png"},
}

ThemeStoreRes =
{
	[131] =
	{
		{2, "theme_store_game/images/puzzle_1.png"},
		{2, "theme_store_game/images/puzzle_2.png"},
		{2, "theme_store_game/images/puzzle_3.png"},
		{2, "theme_store_game/images/puzzle_4.png"},
		{2, "theme_store_game/images/puzzle_5.png"},
		{2, "theme_store_game/images/puzzle_6.png"},
		{2, "theme_store_game/images/puzzle_7.png"},
		{2, "theme_store_game/images/puzzle_8.png"},
		{2, "theme_store_game/images/puzzle_9.png"},
		{2, "theme_store_game/images/puzzle_10.png"},
		{2, "theme_store_game/images/puzzle_11.png"},
		{2, "theme_store_game/images/puzzle_12.png"},
		{2, "theme_store_game/images/puzzle_13.png"},
		{2, "theme_store_game/images/puzzle_14.png"},
		{2, "theme_store_game/images/puzzle_15.png"},
		{2, "theme_store_game/images/puzzle_16.png"},
		{2, "theme_store_game/images/puzzle_17.png"},
		{2, "theme_store_game/images/puzzle_18.png"},
		{2, "theme_store_game/images/ui.png"},
		{2, "theme_store_game/images/popup.png"},

		{2, "theme_store_game/spine/buy/bottom/sd_pingzi_01.png"},
		{2, "theme_store_game/spine/buy/choose_effect/sd_pingzilizi_01.png"},
		{2, "theme_store_game/spine/buy/frame/pingzi_tanchukuang_01.png"},
		{2, "theme_store_game/spine/buy/new_tag/new_01.png"},
		{2, "theme_store_game/spine/buy/puzzle_bg_high/pintu_01.png"},
		{2, "theme_store_game/spine/buy/puzzle_bg_normal/pintu_02.png"},
		{2, "theme_store_game/spine/buy/puzzle_out/sd_pingzi_02.png"},
		{2, "theme_store_game/spine/choose_ablum/ml_01.png"},
		{2, "theme_store_game/spine/choose_buy/sd_kdj_01.png"},
		{2, "theme_store_game/spine/coin_node/frame/jzt_02.png"},
		{2, "theme_store_game/spine/coin_node/logo/jzt_01.png"},
		{2, "theme_store_game/spine/duplicate/liuguang_01.png"},
		{2, "theme_store_game/spine/message/free_frame/cs_freegames_01.png"},
		{2, "theme_store_game/spine/popup/btn/collect_lg_01.png"},
		{2, "theme_store_game/spine/popup/win_frame_common/yingqiankuang_01.png"},
		{2, "theme_store_game/spine/progress/gift_open/liwuhedakai_01.png"},
		{2, "theme_store_game/spine/puzzle/biankuang.png"},
		{2, "theme_store_game/spine/title/biaoti.png"},
	},
	["puzzle2"] = {
		{2, "theme_store_game2/fonts/theme_store_game_font1.png" },
		{2, "theme_store_game2/fonts/theme_store_game_font2.png" },
		{2, "theme_store_game2/fonts/theme_store_game_font3.png" },
		{2, "theme_store_game2/fonts/theme_store_game_font4.png" },
		{2, "theme_store_game2/fonts/theme_store_game_font5.png" },
		{2, "theme_store_game2/images/popup.png" },
		{2, "theme_store_game2/images/puzzle_1.png" },
		{2, "theme_store_game2/images/puzzle_10.png" },
		{2, "theme_store_game2/images/puzzle_11.png" },
		{2, "theme_store_game2/images/puzzle_12.png" },
		{2, "theme_store_game2/images/puzzle_13.png" },
		{2, "theme_store_game2/images/puzzle_14.png" },
		{2, "theme_store_game2/images/puzzle_15.png" },
		{2, "theme_store_game2/images/puzzle_16.png" },
		{2, "theme_store_game2/images/puzzle_17.png" },
		{2, "theme_store_game2/images/puzzle_18.png" },
		{2, "theme_store_game2/images/puzzle_2.png" },
		{2, "theme_store_game2/images/puzzle_3.png" },
		{2, "theme_store_game2/images/puzzle_4.png" },
		{2, "theme_store_game2/images/puzzle_5.png" },
		{2, "theme_store_game2/images/puzzle_6.png" },
		{2, "theme_store_game2/images/puzzle_7.png" },
		{2, "theme_store_game2/images/puzzle_8.png" },
		{2, "theme_store_game2/images/puzzle_9.png" },
		{2, "theme_store_game2/images/ui.png" },
		{2, "theme_store_game2/spine/buy/bottom/sd_pingzi_01.png" },
		{2, "theme_store_game2/spine/buy/choose_effect/sd_pingzilizi_01.png" },
		{2, "theme_store_game2/spine/buy/frame/pingzi_tanchukuang_01.png" },
		{2, "theme_store_game2/spine/buy/new_tag/new_01.png" },
		{2, "theme_store_game2/spine/buy/puzzle_bg_high/pintu_01.png" },
		{2, "theme_store_game2/spine/buy/puzzle_bg_normal/pintu_02.png" },
		{2, "theme_store_game2/spine/buy/puzzle_out/sd_pingzi_02.png" },
		{2, "theme_store_game2/spine/choose_ablum/shu.png" },
		{2, "theme_store_game2/spine/choose_buy/anniu_saoguang.png" },
		{2, "theme_store_game2/spine/coin_node/frame/jzt_02.png" },
		{2, "theme_store_game2/spine/coin_node/logo/toukuiicon.png" },
		{2, "theme_store_game2/spine/duplicate/liuguang_01.png" },
		{2, "theme_store_game2/spine/message/free_frame/cs_freegames_01.png" },
		{2, "theme_store_game2/spine/popup/btn/anniu.png" },
		{2, "theme_store_game2/spine/popup/title_flash/zhuhe.png" },
		{2, "theme_store_game2/spine/popup/win_frame_common/changkuang.png" },
		{2, "theme_store_game2/spine/progress/collect/jindutiaowancheng.png" },
		{2, "theme_store_game2/spine/progress/gift_close/jinbisaoguang.png" },
		{2, "theme_store_game2/spine/progress/gift_open/liewenjinbi.png" },
		{2, "theme_store_game2/spine/puzzle/biankuang.png" },
		{2, "theme_store_game2/spine/title/biaoti.png" },
	},
	puzzle2_h= {
		{2, "theme_store_game2horizon/fonts/theme_store_game_font1.png" },
		{2, "theme_store_game2horizon/fonts/theme_store_game_font2.png" },
		{2, "theme_store_game2horizon/fonts/theme_store_game_font3.png" },
		{2, "theme_store_game2horizon/fonts/theme_store_game_font4.png" },
		{2, "theme_store_game2horizon/fonts/theme_store_game_font5.png" },
		{2, "theme_store_game2horizon/images/popup.png" },
		{2, "theme_store_game2horizon/images/puzzle_1.png" },
		{2, "theme_store_game2horizon/images/puzzle_10.png" },
		{2, "theme_store_game2horizon/images/puzzle_11.png" },
		{2, "theme_store_game2horizon/images/puzzle_12.png" },
		{2, "theme_store_game2horizon/images/puzzle_13.png" },
		{2, "theme_store_game2horizon/images/puzzle_14.png" },
		{2, "theme_store_game2horizon/images/puzzle_15.png" },
		{2, "theme_store_game2horizon/images/puzzle_16.png" },
		{2, "theme_store_game2horizon/images/puzzle_17.png" },
		{2, "theme_store_game2horizon/images/puzzle_18.png" },
		{2, "theme_store_game2horizon/images/puzzle_2.png" },
		{2, "theme_store_game2horizon/images/puzzle_3.png" },
		{2, "theme_store_game2horizon/images/puzzle_4.png" },
		{2, "theme_store_game2horizon/images/puzzle_5.png" },
		{2, "theme_store_game2horizon/images/puzzle_6.png" },
		{2, "theme_store_game2horizon/images/puzzle_7.png" },
		{2, "theme_store_game2horizon/images/puzzle_8.png" },
		{2, "theme_store_game2horizon/images/puzzle_9.png" },
		{2, "theme_store_game2horizon/images/ui.png" },
		{2, "theme_store_game2horizon/spine/buy/bottom/sd_pingzi_01.png" },
		{2, "theme_store_game2horizon/spine/buy/choose_effect/sd_pingzilizi_01.png" },
		{2, "theme_store_game2horizon/spine/buy/frame/kuangsaoguang.png" },
		{2, "theme_store_game2horizon/spine/buy/new_tag/new_01.png" },
		{2, "theme_store_game2horizon/spine/buy/puzzle_bg_high/pintu_01.png" },
		{2, "theme_store_game2horizon/spine/buy/puzzle_bg_normal/pintu_02.png" },
		{2, "theme_store_game2horizon/spine/buy/puzzle_out/sd_pingzi_02.png" },
		{2, "theme_store_game2horizon/spine/choose_ablum/shu.png" },
		{2, "theme_store_game2horizon/spine/choose_buy/anniu_saoguang.png" },
		{2, "theme_store_game2horizon/spine/coin_node/frame/jzt_02.png" },
		{2, "theme_store_game2horizon/spine/coin_node/logo/toukuiicon.png" },
		{2, "theme_store_game2horizon/spine/duplicate/liuguang_01.png" },
		{2, "theme_store_game2horizon/spine/message/free_frame/cs_freegames_01.png" },
		{2, "theme_store_game2horizon/spine/popup/btn/anniu.png" },
		{2, "theme_store_game2horizon/spine/popup/title_flash/zhuhe.png" },
		{2, "theme_store_game2horizon/spine/popup/win_frame_common/changkuang.png" },
		{2, "theme_store_game2horizon/spine/progress/collect/jindutiaowancheng.png" },
		{2, "theme_store_game2horizon/spine/progress/gift_close/jinbisaoguang.png" },
		{2, "theme_store_game2horizon/spine/progress/gift_open/liewenjinbi.png" },
		{2, "theme_store_game2horizon/spine/puzzle/biankuang.png" },
		{2, "theme_store_game2horizon/spine/title/biaotisaoguang.png" },
	},

}

ThemePngs = 
{
	[188] = {
		{1, "font/theme188_font_1.png" },
		{1, "font/theme188_font_2.png" },
		{1, "font/theme188_font_3.png" },
		{1, "font/theme188_font_4.png" },
		{1, "font/theme188_font_5.png" },
		{1, "font/theme188_font_6.png" },
		{1, "font/theme188_font_7.png" },
		{1, "font/theme188_font_j.png" },
		{1, "font/theme188_font_j1.png" },
		{1, "font/theme188_font_j2.png" },
		{1, "image/bg/theme188_bg_map.png" },
		{1, "image/paytable/paytable.png" },
		{1, "image/plist/base.png" },
		{1, "image/plist/map.png" },
		{1, "image/plist/symbol.png" },
		{1, "spine/base/188_cp_01.png" },
		{1, "spine/base/base_bj_01.png" },
		{1, "spine/base/basezhousi_01.png" },
		{1, "spine/base/freegame_bj_01.png" },
		{1, "spine/base/psd_01.png" },
		{1, "spine/base/qipanshandian.png" },
		{1, "spine/base/scatter_jl_01.png" },
		{1, "spine/base/shengbei01.png" },
		{1, "spine/base/zhongjianjili.png" },
		{1, "spine/base/zhongjianlizi.png" },
		{1, "spine/collect_progress/lock.png" },
		{1, "spine/collect_progress/shandian_icon.png" },
		{1, "spine/collect_progress/sjt_idle_01.png" },
		{1, "spine/collect_progress/sjt_jm_01.png" },
		{1, "spine/collect_progress/sjt_sz_01.png" },
		{1, "spine/dialog/deal/collectanniu.png" },
		{1, "spine/dialog/deal/jiesuan.png" },
		{1, "spine/dialog/deal/startanniu.png" },
		{1, "spine/dialog/fangxing.png" },
		{1, "spine/dialog/free/fgtanchuang.png" },
		{1, "spine/dialog/takeit/keepanniu.png" },
		{1, "spine/dialog/win_jp/jptanchuang.png" },
		{1, "spine/item/1/wild_01.png" },
		{1, "spine/item/2/zhousi_01.png" },
		{1, "spine/item/3/m2_01.png" },
		{1, "spine/item/4/xianglian_01.png" },
		{1, "spine/item/5/jiezhi_01.png" },
		{1, "spine/item/6/yaodai01.png" },
		{1, "spine/item/7/shouzhuo_01.png" },
		{1, "spine/item/8/scatter_01.png" },
		{1, "spine/item/9/bouns_01.png" },
		{1, "spine/item/kuang/shandiankuang_01.png" },
		{1, "spine/kuang/zjlx_01.png" },
		{1, "spine/map/bianshen.png" },
		{1, "spine/map/dashengbeixunhuan.png" },
		{1, "spine/map/jiangbeichuxian.png" },
		{1, "spine/map/shengbeifei.png" },
		{1, "spine/map/shengbeixuanzhong.png" },
		{1, "spine/map/shengbeixunhuan.png" },
		{1, "spine/map/tihuan1000X.png" },
		{1, "spine/map/tuitukuang.png" },
		{1, "spine/map/xiaosun.png" },
		{1, "spine/map/zhalizi.png" },
		{1, "spine/paytable/dantu/CX_saoguang01.png" },
		{1, "spine/paytable/dantu/elephant_gl01.png" },
		{1, "spine/paytable/spine/back_to_game01.png" },
		{1, "spine/win_jp/basezhousi_jp_psd_01.png" },
		{1, "spine/win_jp/jp_k_xz_01.png" },
	},
}


-- 一代puzzle
ThemeStoreRes[130] = ThemeStoreRes[131]
ThemeStoreRes[132] = ThemeStoreRes[131]
ThemeStoreRes[135] = ThemeStoreRes[131]
ThemeStoreRes[151] = ThemeStoreRes[131]
ThemeStoreRes[161] = ThemeStoreRes[131]
ThemeStoreRes[169] = ThemeStoreRes[131]

-- 二代puzzle
ThemeStoreRes[171] = ThemeStoreRes["puzzle2"]
ThemeStoreRes[184] = ThemeStoreRes["puzzle2"]
ThemeStoreRes[190] = ThemeStoreRes["puzzle2"]
ThemeStoreRes[204] = ThemeStoreRes["puzzle2_h"]

---@desc 竖版小老虎机
ThemeStoreRes[189] = ThemePngs[2008]
ThemeStoreRes[230] = ThemePngs[2008]
ThemeStoreRes[239] = ThemePngs[2011]
