

LoadingLabelDesc = {
	[103] = {
		["type"] 	= 1,
		["value"] 	= {
			[1] = "6",
			[2]	= "6",
			[3]	= "5",
			[4]	= "5",
		},
	},
	[104] = {
		["type"] 	= 1,
		["value"] 	= {
			[1] = "6",
			[2]	= "6",
			[3]	= "5",
			[4]	= "5",
		},
	},

	[603] = {
		["type"] 	= 1,
		["value"] 	= {
			[1] = "5",
			[2]	= "5",
			[3]	= "5",
			[4]	= "5",
		},
	},
	[604] = {
		["type"] 	= 1,
		["value"] 	= {
			[1] = "5",
			[2]	= "5",
			[3]	= "5",
			[4]	= "5",
		},
	},
}

LoadingTipsDesc  = {
	{"HIGHER BETS, MORE REWARDS!"},
	{"MAKE QUALIFIED SPIN TO EARN LOUNGE POINTS！"},
	{"SPIN IN ANY SLOT TO COLLECT SPECIAL PROPS!"},
	{"EVERY 100 SPINS IN ANY SLOT", "BRINGS YOU A SHOPPING BAG!"},
	{"BET HIGHER TO RECEIVE MORE AND RARER HAMMERS！"},
	{"EARN 15000 LOUNGE POINTS TO WIN A DIAMOND", "FOR LOUNGE PASS!"},
	{"BET HIGHER FOR MORE AND BETTER STAMPS!"},
	{"USE BOUNS STAMPS TO COLLECT STAMPS", "YOU HAVEN'T HAD YET!"},
	{"ENJOY FASTER LEVEL UP AND SPIN REWARDS", "IN DIAMOND LOUNGE!"},
	{"BUY LEVEL BURST TO MUTIPLY YOUR", "LEVEL-UP REWARD 25x!"},
	{"BET HIGHER TO GET A CHANCE TO WIN JACKPOT!"},
	{"SHARE Slots Golden WITH YOUR BEST FRIENDS!"},
	{"BUY SLOT BLAST TO DOUBLE YOUR REWARDS", "FROM SLOT OF CASH! "},
	{"ACTIVATE SPIN UP AFTER PURCHASE", "TO GET EXTRA COINS!"},
	{"EXCLUSIVE AVATOR IN MISSION PASS!"},
	{" GET BONUS VOUCHER WITH ANY PURCHASE", "TO SEND YOUR FRIENDS GIFT COINS!"},
	{"PLAY RED SCRATCH EVERY SINGLE HOUR WITH SPEEDY!"},
	{"GATHER YOUR CLUBMATES TO PLAY", "AND WIN THE CLUB KEY!"},
	{"KEEP SPINING TO UPGRADE YOUR PERSONAL CLUB CHEST!"},
	{"COLLECT BADGES IN SELECTED SLOTS!"},
	{"SPIN IN FRENZY FEATURES' SLOT TO WIN FRENZY STAMPS!"},
	{"GET FREEBIES BY SHAREING Slots Golden!"},
}

LoadingTipsConfig = {
	desc = {
		{"HIGHER BETS, MORE REWARDS!"},
		-- {"MAKE QUALIFIED SPIN TO EARN LOUNGE POINTS！"},
		-- {"SPIN IN ANY SLOT TO COLLECT SPECIAL PROPS!"},
		-- {"EVERY 100 SPINS IN ANY SLOT", "BRINGS YOU A SHOPPING BAG!"},
		-- {"BET HIGHER TO RECEIVE MORE AND RARER DEPOTS！"},
		-- {"EARN 15000 LOUNGE POINTS TO WIN A DIAMOND", "FOR LOUNGE PASS!"},
		-- {"BET HIGHER FOR MORE AND BETTER STAMPS!"},
		-- {"USE BOUNS STAMPS TO COLLECT STAMPS", "YOU HAVEN'T HAD YET!"},
		-- {"ENJOY FASTER LEVEL UP AND SPIN REWARDS", "IN DIAMOND LOUNGE!"},
		-- {"BUY LEVEL BURST TO MUTIPLY YOUR", "LEVEL-UP REWARD 25x!"},
		-- {"BET HIGHER TO GET A CHANCE TO WIN JACKPOT!"},
		-- {"SHARE Slots Golden WITH YOUR BEST FRIENDS!"},
		-- {"BUY SLOT BLAST TO DOUBLE YOUR REWARDS", "FROM SLOT OF CASH! "},
		-- {"ACTIVATE SPIN UP AFTER PURCHASE", "TO GET EXTRA COINS!"},
		-- {"EXCLUSIVE AVATOR IN MISSION PASS!"},
		{" GET BONUS VOUCHER WITH ANY PURCHASE", "TO SEND YOUR FRIENDS GIFT COINS!"},
		-- {"PLAY RED SCRATCH EVERY SINGLE HOUR WITH SPEEDY!"},
		-- {"GATHER YOUR CLUBMATES TO PLAY", "AND WIN THE CLUB KEY!"},
		-- {"KEEP SPINING TO UPGRADE YOUR PERSONAL CLUB CHEST!"},
		-- {"COLLECT BADGES IN SELECTED SLOTS!"},
		{"SPIN IN FRENZY FEATURES' SLOT TO WIN FRENZY STAMPS!"},
		-- {"GET FREEBIES BY SHAREING Slots Golden!"},
	},
	bar = {
		[0] = { -- 横版
			moveY = 9,
			barY = -280.5,
			barBgY = -280.5 + 1.5,
			barScale = 1.46, -- 1.465
			tipBarDis = -25,
			tipLbDis = 28,
			lbScale = {1,1},
			lbCount = 1,
 		},
		[1] = { -- 竖版
			moveY = 25, --29,
			barY = -529.5,
			barBgY = -280.5 + 1.5,
			barScale = 0.69,
			tipBarDis = -25,
			tipLbDis = 28,
			lbScale = {(1/0.69)*0.94, 0.94},
			lbCount = 2,
		}
	}
}

ThemeMuti = {
	[188] = {
		["1"]  = {"5 - 20000",  "4 - 8000"},
		["2"]  = {"5 - 10000",  "4 - 3000",   "3 - 1000"},
		["3"]  = {"5 - 6000",  "4 - 2000",   "3 - 500"},
	},
}





